import React from 'react';
import ReactDOM from 'react-dom/client';
import './gasFetchCompat';
import './gasSaveJsonpChunkPatch';
import App from './App';
import './personalizationSync';
import './appDataPreloader';
import './desktopInteractionFix';
import './profileWeekTableFix';
import './taskViewEnhancer';
import './startMenuListEnhancer';
import './mobileAppShell';
import './scoreboardMobilePolish';
import './scoreboardMobileFinalFix';
import './scoreboardMobileOcdFix';
import './index.css';
import './login-responsive-polish.css';
import './desktopBrandPanelWide.css';
import './scoreboard-modal-fix.css';
import './scoreboard-final-fix.css';
import './scoreboard-theme-animation.css';
import './scoreboard-final-polish.css';
import './scoreboardHonorsAndChartPolish.css';
import './scoreboardMobileLatestFix.css';
import './scoreboardMobileEmergencyPatch';
import './scoreboardMobileStudentDetailCardsPatch';
import './scoreboardMultiGroupFilter.css';
import './scoreboardGroupStatsChartV2.css';
import './scoreboardSoftLightTheme.css';
import './scoreboardScoreEditorLayoutPolish.css';
import './scoreboardScoringModalInteractionPolish.css';
import './scoreboardModalFinalOcdPatch.css';
import './scoreboardModalStackAndFooterFix.css';
import './scoreboardFilterSelectHardFix.css';
import './createWeekModal.css';
import './scoreboardLiveNotifications.css';
import './scoreboardModalInputCleanup';
import './scoreboardExcelExport';
import './scoreboardScreenshotCapture';
import './scoreboardScreenshotFullPreviewFix.css';
import './shotFix.css';
import './scoreboardScreenshotAllClassCompact';
import './scoreboardScreenshotGroupFullDetailsFix';
import './overlayThemeSync';
import './overlayLightDarkFix.css';
import './overlayToastAndFooterFix.css';
import './globalLoadingThemeFix';
import './globalLoadingThemeFix.css';
import './scoreboardMobileScoreEditorFix.css';
import './scoreboardMobileLightThemeHardFix.css';
import './scoreboardMobileScoreEditorRuntimeFix';
import './scoreboardPositiveColor.css';
import './settingsDisplayOptionsPatch';
import './messagesThreadActionsPatch';
import './messagesSuggestionOpenPatch';
import './messagesPermissionRoleGuard';
import './messagesBubbleActionsPatch';
import './messagesMessengerBubblePolish.css';
import './messagesLightModeHardFix.css';
import './messagesServerReloadHardFix';
import './desktopLightThemeHardFix.css';
import './desktopDarkBackgroundSoftFix.css';
import './desktopDriveWallpaperSync';
import './desktopDriveErrorPolish';
import './desktopWallpaperStabilityFix';
import './settingsWallpaperUiPolish.css';
import './settingsToggleAccentFix.css';
import './desktopCleanWallpaperMode.css';
import './taskFocusSwitchDarkOnFix.css';
import './profileWeekScoreChartPatch';
import './profileWeekSwitcherPolish.css';
import './messagesMobileInterfaceFix.css';
import './messagesMessengerMobileController';
import './messagesMessengerMobileFinal.css';
import './messagesMobileCleanFinal.css';
import './messagesMobileBackVisibleFix.css';
import './seatingMapStableApp';
import './seatingHideStudentCount.css';
import './seatingSheetDatabasePatch';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
