const W = "#a3k64-seating-window";
const GAS = String(import.meta.env.VITE_GAS_WEB_APP_URL || "").trim();
const CID = "a3k64-seating-sheet-current-id-v1";
let ready = false;
let guard = false;
let count = 0;
let timer = 0;
type Status = "private" | "preview" | "published";
type Mode = "view" | "edit";
const perms = ["move", "save", "create", "restore", "random", "export"];
function norm(v: unknown) { return String(v || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/đ/g, "d").replace(/[^a-z0-9@._-]+/g, " ").trim(); }
function compact(v: unknown) { return norm(v).replace(/\s+/g, ""); }
function title() { return document.querySelector<HTMLElement>(`${W} .seat-ctrl-trigger span`)?.textContent?.trim() || "Sơ đồ hiện tại"; }
function storedId() { const id = localStorage.getItem(CID) || ""; return id && id !== "default" ? id : ""; }
function win() { return document.querySelector<HTMLElement>(W); }
function visible() { const el = win(); if (!el) return false; const r = el.getBoundingClientRect(); const s = getComputedStyle(el); return r.width > 0 && r.height > 0 && s.display !== "none" && s.visibility !== "hidden"; }
function actor() { try { const s = JSON.parse(localStorage.getItem("a3k64-login-session-v1") || "null"); const u = s?.user || s || {}; return { name: String(u.name || u.fullName || u.studentName || u.displayName || u.hoTen || u.fullname || u.username || ""), email: String(u.email || u.username || ""), username: String(u.username || u.email || ""), role: String(u.role || u.userRole || "") }; } catch { return { name: "", email: "", username: "", role: "" }; } }
function admin() { const r = compact(actor().role); return r.includes("gvcn") || r.includes("loptruong") || r.includes("bithu") || r.includes("admin"); }
function status(v: unknown): Status { const x = compact(v); if (x === "preview" || x === "xemtruoc") return "preview"; if (["published", "publish", "public", "congbo", "congkhai", "scheduled", "hengio"].includes(x)) return "published"; return "private"; }
function pmode(v: unknown): Mode { const x = compact(v); return x === "edit" || x === "sua" ? "edit" : "view"; }
function parsePerms(v: unknown) { let d: any = v || {}; if (typeof d === "string") { try { d = JSON.parse(d); } catch { d = {}; } } const out: Record<string, boolean> = {}; perms.forEach((k) => out[k] = Boolean(d?.[k])); return out; }
function normalizeAccess(raw: any) { const s = raw?.access || raw?.data?.access || raw?.config || raw?.data?.config || raw; return { chartId: String(s?.chartId || s?.chart_id || s?.id || storedId()), chartTitle: String(s?.chartTitle || s?.chart_title || s?.title || title()), status: status(s?.status), previewStudents: String(s?.previewStudents || s?.preview_students || ""), publishAt: String(s?.publishAt || s?.publish_at || ""), previewMode: pmode(s?.previewMode || s?.preview_mode), previewPermissions: parsePerms(s?.previewPermissions || s?.preview_permissions), backendOk: Boolean(s) }; }
function gas(action: string, payload?: unknown): Promise<any> { if (!GAS) return Promise.reject(new Error("Thiếu VITE_GAS_WEB_APP_URL")); return new Promise((resolve, reject) => { const cb = `__a3vg_${Date.now()}_${Math.random().toString(36).slice(2)}`; const callbacks = window as typeof window & Record<string, unknown>; const script = document.createElement("script"); const url = new URL(GAS); let done = false; let timeout = 0; url.searchParams.set("action", action); url.searchParams.set("callback", cb); url.searchParams.set("t", String(Date.now())); if (payload !== undefined) url.searchParams.set("payload", JSON.stringify(payload)); callbacks[cb] = (json: any) => { if (done) return; done = true; clearTimeout(timeout); delete callbacks[cb]; script.remove(); if (json?.ok === false || json?.data?.ok === false) reject(new Error(String(json.error || json.data?.error || "Backend lỗi"))); else resolve(json?.data || json); }; script.onerror = () => { if (done) return; done = true; clearTimeout(timeout); delete callbacks[cb]; script.remove(); reject(new Error("Không gọi được Apps Script")); }; timeout = window.setTimeout(() => { if (done) return; done = true; delete callbacks[cb]; script.remove(); reject(new Error("Apps Script phản hồi quá lâu")); }, 7000); script.src = url.toString(); document.head.appendChild(script); }); }
async function resolveChart() { const t = title(); const id = storedId(); try { const raw = await gas("listSeatingCharts", {}); const list = raw?.charts || raw?.data?.charts || []; const key = compact(t); const n = String(t).match(/\d+/)?.[0] || ""; const found = (id ? list.find((c: any) => String(c.id) === id) : null) || list.find((c: any) => compact(c.title) === key) || (n ? list.find((c: any) => (String(c.title).match(/\d+/)?.[0] || "") === n && compact(c.title).includes("sodo")) : null) || list.find((c: any) => c.active) || null; return { chartId: String(found?.id || id || ""), chartTitle: String(found?.title || t) }; } catch { return { chartId: id, chartTitle: t }; } }
async function load() { try { const r = await resolveChart(); const a = normalizeAccess(await gas("getSeatingAccess", r)); if (a.chartId) localStorage.setItem(CID, a.chartId); return a; } catch (e) { console.warn("Không đọc được quyền sơ đồ:", e); return { chartId: "", chartTitle: title(), status: "private" as Status, previewStudents: "", publishAt: "", previewMode: "view" as Mode, previewPermissions: {}, backendOk: false }; } }
function tokens() { const a = actor(); const out = new Set<string>(); [a.name, a.email, a.username].forEach((v) => { if (v) out.add(v); const b = String(v || "").split("@")[0]; if (b) out.add(b); const nd = b.replace(/[0-9_.-]+/g, " ").trim(); if (nd) out.add(nd); }); return Array.from(out).map(compact).filter(Boolean); }
function inPreview(a: any) { const list = String(a.previewStudents || "").split(/[\n,;]+/).map(compact).filter(Boolean); const user = tokens(); return !!list.length && user.some((u) => list.some((t) => u.includes(t) || t.includes(u))); }
function published(a: any) { if (a.status !== "published") return false; const ms = new Date(a.publishAt || "").getTime(); return !Number.isFinite(ms) || !ms || Date.now() >= ms; }
function deniedText(a: any) { if (!a.backendOk) return "Không xác minh được quyền xem từ backend.\nVui lòng tải lại hoặc báo quản trị viên."; if (a.status === "published" && a.publishAt && !published(a)) return "Sơ đồ đã được lên lịch công bố.\nMở lúc " + new Date(a.publishAt).toLocaleString("vi-VN") + "."; if (a.status === "preview") return "Sơ đồ đang ở chế độ xem trước.\nTài khoản này chưa nằm trong danh sách được xem."; return "Sơ đồ chỗ ngồi đang ở chế độ riêng tư."; }
function style() { if (document.getElementById("a3-seat-view-gate-lite-style")) return; const s = document.createElement("style"); s.id = "a3-seat-view-gate-lite-style"; s.textContent = `html.a3-seat-viewer-denied ${W} .stable-seat-board,html.a3-seat-viewer-denied ${W} .stable-seat-student-panel{visibility:hidden!important;opacity:0!important;pointer-events:none!important}html.a3-seat-viewer-denied ${W}::after{white-space:pre-line;content:attr(data-seat-gate-message);position:absolute;inset:76px 22px 22px;z-index:80;display:flex;align-items:center;justify-content:center;text-align:center;padding:24px;border:1px solid #cbd5e1;border-radius:22px;background:rgba(255,255,255,.985);color:#0f172a;font-weight:1000;font-size:18px;line-height:1.5;box-shadow:0 24px 70px rgba(15,23,42,.16)}#a3-seat-view-gate-toast{position:fixed;left:50%;top:72px;transform:translateX(-50%);z-index:1000000;display:flex;align-items:center;gap:10px;padding:9px 13px;border:1px solid rgba(20,184,166,.7);border-radius:15px;background:rgba(255,255,255,.985);color:#0f172a;box-shadow:0 18px 50px rgba(15,23,42,.18);font-size:13px;font-weight:900;pointer-events:none}#a3-seat-view-gate-toast .spin{width:14px;height:14px;border-radius:999px;border:2px solid rgba(15,23,42,.16);border-top-color:var(--desktop-accent,#14b8a6);animation:a3vg .72s linear infinite}#a3-seat-view-gate-toast.ok .spin{animation:none;border-color:var(--desktop-accent,#14b8a6);background:var(--desktop-accent,#14b8a6);box-shadow:inset 0 0 0 4px #fff}@keyframes a3vg{to{transform:rotate(360deg)}}`; document.head.appendChild(s); }
function toast(msg: string, ok = false) { if (!visible()) return; document.getElementById("a3-seat-view-gate-toast")?.remove(); const t = document.createElement("div"); t.id = "a3-seat-view-gate-toast"; t.className = ok ? "ok" : "checking"; t.innerHTML = `<span class="spin"></span><span>${msg}</span>`; document.body.appendChild(t); setTimeout(() => t.remove(), ok ? 1200 : 2600); }
function setState(allow: boolean, readonly: boolean, msg = "", a?: any) { const root = document.documentElement; root.classList.remove("a3-seat-viewer-checking"); root.classList.toggle("a3-seat-viewer-denied", !allow); root.classList.toggle("a3-seat-viewer-readonly", allow && readonly); root.classList.toggle("a3-seat-preview-editor", allow && !readonly && !admin()); if (a) { root.dataset.seatPreviewMode = a.previewMode || "view"; root.dataset.seatPreviewPerms = Object.entries(a.previewPermissions || {}).filter(([, v]) => v).map(([k]) => k).join(","); } const el = win(); if (el) el.dataset.seatGateMessage = msg; seatViewLastAllowed = allow; }
function bindGuard() { if (guard) return; guard = true; ["dragstart", "dragover", "drop", "contextmenu"].forEach((type) => document.addEventListener(type, (e) => { const target = e.target as HTMLElement | null; if (!document.documentElement.classList.contains("a3-seat-viewer-readonly")) return; if (!target?.closest?.(W)) return; e.preventDefault(); e.stopPropagation(); if ("stopImmediatePropagation" in e) e.stopImmediatePropagation(); }, true)); }
async function check() { style(); bindGuard(); if (!visible()) { document.documentElement.classList.remove("a3-seat-viewer-denied", "a3-seat-viewer-readonly", "a3-seat-preview-editor"); seatViewLastAllowed = false; return; } if (admin()) { setState(true, false); return; } if (!seatViewLastAllowed && !document.documentElement.classList.contains("a3-seat-viewer-denied")) toast("Đang kiểm tra quyền xem sơ đồ..."); const a = await load(); if (!visible()) return; if (inPreview(a)) { const ro = a.previewMode !== "edit"; setState(true, ro, "", a); if (!seatViewLastAllowed) toast(ro ? "Đã xác nhận quyền xem trước." : "Đã xác nhận quyền sửa xem trước.", true); } else if (published(a)) { setState(true, true, "", a); if (!seatViewLastAllowed) toast("Sơ đồ đã được công bố.", true); } else setState(false, true, deniedText(a), a); }
function boot() { if (ready) return; ready = true; style(); bindGuard(); void check(); timer = window.setInterval(() => { void check(); count++; if (count > 120 && timer) clearInterval(timer); }, 15000); window.addEventListener("a3k64:seating-changed", () => setTimeout(() => void check(), 80)); window.addEventListener("a3k64:seating-access-updated", () => setTimeout(() => void check(), 80)); }
if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot); else boot();
export {};
